### ISSUE TITLE
Possibly replace EncFS with eCryptfs

### ISSUE THREAD

**Issue by rteijeiro** [martinseener/Hebato#10]
First of all, thanks for your script. It's really useful.

As it seems that EncFS is not secure anymore (https://askubuntu.com/questions/813290/encfs-insecure-what-to-use-now) maybe it's a good idea to replace it with eCryptfs?

**Comment by rteijeiro** [comment]
Maybe a duplicated or replacement of #7

**Comment by martinseener** [comment]
I'm sorry, i stopped maintaining Hebato in favor of other/better tools.
