### ISSUE TITLE
Throughput slow

### ISSUE THREAD

**Issue by kingfisher77** [martinseener/Hebato#9]
We set everything up like suggested. Functionwise everything is like expected. But the speed is very slow. We make around 5MB/s. Direkt copy on the sshfs-mount without encfs reaches up to 30MB/s.

Do you experience the same throughput? What do think, are there some adjustments we can try?

**Comment by martinseener** [comment]
Hmm it depends on what you're copying and on which device you're doing it. EncFS does AES encryption on the fly (thus requires (lot's) of CPU power if the CPU has noe AES-NI hardware accel. (thus it's quite slow on raspberries for example) and if you backup lots of small files with rdiff-backup (which is basically using rsync) then it's slower as well compared to copy one large file where you can saturate your bandwith

**Comment by kingfisher77** [comment]
Thank you for your answer - meanwhile we switched to cifs-mount, 
loop-mount of an img-File inside cifs-mount and encfs (all activated by 
autofs). With this setup rsync can maintain all file permissions. And 
this setup achieves around 90-100 MByte/s.

On 8 Jun 2017, at 8:18, Martin wrote:

> Hmm it depends on what you're copying and on which device you're doing 
> it. EncFS does AES encryption on the fly (thus requires (lot's) of CPU 
> power if the CPU has noe AES-NI hardware accel. (thus it's quite slow 
> on raspberries for example) and if you backup lots of small files with 
> rdiff-backup (which is basically using rsync) then it's slower as well 
> compared to copy one large file where you can saturate your bandwith
>
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/martinseener/Hebato/issues/9#issuecomment-307009652




-- 
Tobias Kirchhofer
tobias@kirchhofer.net

**Comment by martinseener** [comment]
I'm sorry, i stopped maintaining Hebato in favor of other/better tools.
